# Generated by Django 4.2.7 on 2025-07-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='指導場所')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='school.school')),
            ],
            options={
                'verbose_name': '指導場所',
                'verbose_name_plural': '指導場所',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='順番')),
                ('name', models.CharField(max_length=50, verbose_name='曜日名')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='school.school')),
            ],
            options={
                'verbose_name': '曜日',
                'verbose_name_plural': '曜日',
                'ordering': ['order'],
            },
        ),
    ]
