# Generated by Django 4.2.7 on 2025-07-10 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='コマ開始時間')),
                ('end_time', models.TimeField(verbose_name='コマ終了時間')),
                ('is_empty', models.BooleanField(default=False, verbose_name='このシフトを空けるかどうか')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='config.place', verbose_name='シフト場所')),
                ('teacher', models.ManyToManyField(blank=True, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='シフト割当講師')),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FixedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='固定シフト開始時間')),
                ('end_time', models.TimeField(verbose_name='固定シフト終了時間')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='固定シフト内容')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.day', verbose_name='曜日')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_shifts', to='config.place', verbose_name='固定シフト場所')),
                ('teacher', models.ManyToManyField(blank=True, related_name='fixed_shifts', to=settings.AUTH_USER_MODEL, verbose_name='固定シフト割当講師')),
            ],
            options={
                'verbose_name': '固定シフト',
                'verbose_name_plural': '固定シフト',
                'ordering': ['day__order', 'start_time'],
            },
        ),
    ]
