# Generated by Django 4.2.7 on 2025-07-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='学校名')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='始業時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終業時間')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
    ]
